#1.서버 포트 설정
server:
    port: 8082

#2.DB연결 정보
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc.mariadb://db.newlecture.com/mayodb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mayo
    password: 240219

#3.Mybatis 설정 정보
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.Mapper.xml
  type-aliases-package: kor.co.mayo.dreamon.entity 

#4.로그설정
logging:
  level:
    kor:
      co:
        mayo:
          dreamon:
            repository: DEBUG  

# spring:
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: ryunji1990@gmail.com
#     password: uibm eipw ptsa ef
#     properties:
#       mail:
#         smtp:
#           starttls:
#             enable: true
#             required: true
#           auth: true
#           connectiontimeout: 5000
#           timeout: 5000
#           writetimeout: 5000